#!/usr/bin/env node

/**
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE.
 * This is the CLI entry point for designloom MCP server.
 * The actual implementation is in index.ts
 */

import { startMcpServer } from "./index.js";
import { resolveDataPath } from "./path-resolver.js";

/**
 * Get the data path from environment or default.
 * Checks DESIGNLOOM_DATA_PATH environment variable first,
 * then defaults to ./design/designloom in current directory.
 * Uses git-aware path resolution for worktree support.
 * @returns Resolved absolute path to design documents
 */
function getDataPath(): string {
    // Check for DESIGNLOOM_DATA_PATH environment variable
    const envPath = process.env.DESIGNLOOM_DATA_PATH;
    if (envPath) {
        return resolveDataPath(envPath);
    }

    // Default to ./design/designloom - resolves to main repo in worktrees
    return resolveDataPath("./design/designloom");
}

// Start the server
const dataPath = getDataPath();
startMcpServer(dataPath).catch((error: unknown) => {
    const message = error instanceof Error ? error.message : String(error);
    console.error("Failed to start Designloom server:", message);
    process.exit(1);
});
