#!/usr/bin/env node

/**
 * THIS FILE IS AUTO GENERATED: DO NOT EDIT THIS FILE.
 * This is the CLI entry point for designloom MCP server.
 * The actual implementation is in index.ts and browser/index.ts
 */

import { Command } from "commander";

import { startBrowser } from "./browser/index.js";
import { startMcpServer } from "./index.js";
import { resolveDataPath } from "./path-resolver.js";

/**
 * Get the data path from environment or default.
 * Checks DESIGNLOOM_DATA_PATH environment variable first,
 * then defaults to ./design/designloom in current directory.
 * Uses git-aware path resolution for worktree support.
 * @returns Resolved absolute path to design documents
 */
function getDataPath(): string {
    // Check for DESIGNLOOM_DATA_PATH environment variable
    const envPath = process.env.DESIGNLOOM_DATA_PATH;
    if (envPath) {
        return resolveDataPath(envPath);
    }

    // Default to ./design/designloom - resolves to main repo in worktrees
    return resolveDataPath("./design/designloom");
}

const program = new Command();

program
    .name("designloom")
    .description("MCP server for workflow-driven design management")
    .version("0.1.0");

// Default command (MCP server) - backward compatible
program
    .command("serve", { isDefault: true })
    .description("Start MCP server (default)")
    .action(async () => {
        const dataPath = getDataPath();
        try {
            await startMcpServer(dataPath);
        } catch (error: unknown) {
            const message =
                error instanceof Error ? error.message : String(error);
            console.error("Failed to start Designloom server:", message);
            process.exit(1);
        }
    });

// Browse command - web interface
program
    .command("browse")
    .description("Open browser interface to explore design artifacts")
    .option("-p, --port <port>", "API server port (frontend is port+1)", "9050")
    .option("--no-open", "Don't open browser automatically")
    .action(async (options: { port: string; open: boolean }) => {
        const dataPath = getDataPath();
        try {
            await startBrowser(dataPath, {
                port: parseInt(options.port, 10),
                open: options.open,
            });
        } catch (error: unknown) {
            const message =
                error instanceof Error ? error.message : String(error);
            console.error("Failed to start Designloom browser:", message);
            process.exit(1);
        }
    });

program.parse();
